-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 15:22:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ruoka_netista
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ruoka_netista
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ruoka_netista` DEFAULT CHARACTER SET utf8 ;
USE `ruoka_netista` ;

-- -----------------------------------------------------
-- Table `ruoka_netista`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Owner` (
  `idOwner` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Kayttajatunnus` VARCHAR(45) NULL,
  `Salasana` VARCHAR(45) NULL,
  `Osoite` VARCHAR(45) NULL,
  PRIMARY KEY (`idOwner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Restaurants` (
  `idRestaurants` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Osoite` VARCHAR(45) NULL,
  `Ravintolan_tyypi` VARCHAR(45) NULL,
  `Hintataso` VARCHAR(45) NULL,
  `Aukioloajat` VARCHAR(45) NULL,
  `Kuva` VARCHAR(45) NULL,
  PRIMARY KEY (`idRestaurants`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Owner_Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Owner_Restaurants` (
  `Owner_idOwner` INT NOT NULL,
  `Restaurants_idRestaurants` INT NOT NULL,
  PRIMARY KEY (`Owner_idOwner`, `Restaurants_idRestaurants`),
  INDEX `fk_Owner_Restaurants_Restaurants1_idx` (`Restaurants_idRestaurants` ASC) VISIBLE,
  CONSTRAINT `fk_Owner_Restaurants_Owner`
    FOREIGN KEY (`Owner_idOwner`)
    REFERENCES `ruoka_netista`.`Owner` (`idOwner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Owner_Restaurants_Restaurants1`
    FOREIGN KEY (`Restaurants_idRestaurants`)
    REFERENCES `ruoka_netista`.`Restaurants` (`idRestaurants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Menu_Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Menu_Restaurant` (
  `Restaurants_idRestaurants` INT NOT NULL,
  `Menu_idMenu` INT NOT NULL,
  PRIMARY KEY (`Restaurants_idRestaurants`, `Menu_idMenu`),
  INDEX `fk_Menu_Restaurant_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_Restaurant_Restaurants1`
    FOREIGN KEY (`Restaurants_idRestaurants`)
    REFERENCES `ruoka_netista`.`Restaurants` (`idRestaurants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menu_Restaurant_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `ruoka_netista`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Kayttajatunnus` VARCHAR(45) NULL,
  `Salasana` VARCHAR(45) NULL,
  `Osoite` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Order_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Order_history` (
  `idOrder_history` INT NOT NULL,
  `Paiva` DATE NULL,
  `Restaurants_idRestaurants` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idOrder_history`),
  INDEX `fk_Order_history_Restaurants1_idx` (`Restaurants_idRestaurants` ASC) VISIBLE,
  INDEX `fk_Order_history_Customer1_idx` (`Customer_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Order_history_Restaurants1`
    FOREIGN KEY (`Restaurants_idRestaurants`)
    REFERENCES `ruoka_netista`.`Restaurants` (`idRestaurants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_history_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `ruoka_netista`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Dishes` (
  `idDishes` INT NOT NULL AUTO_INCREMENT,
  `Nimi` VARCHAR(45) NULL,
  `Kuvaus` VARCHAR(45) NULL,
  `Hinta` VARCHAR(45) NULL,
  `Tuotekategoria` VARCHAR(45) NULL,
  `Kuva` VARCHAR(45) NULL,
  `Menu_idMenu` INT NOT NULL,
  PRIMARY KEY (`idDishes`, `Menu_idMenu`),
  INDEX `fk_Dishes_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_Dishes_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `ruoka_netista`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ruoka_netista`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ruoka_netista`.`Orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `Dishes_idDishes` INT NOT NULL,
  `Dishes_Menu_idMenu` INT NOT NULL,
  `Order_history_idOrder_history` INT NOT NULL,
  PRIMARY KEY (`idOrders`, `Dishes_idDishes`, `Dishes_Menu_idMenu`, `Order_history_idOrder_history`),
  INDEX `fk_Orders_Dishes1_idx` (`Dishes_idDishes` ASC, `Dishes_Menu_idMenu` ASC) VISIBLE,
  INDEX `fk_Orders_Order_history1_idx` (`Order_history_idOrder_history` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Dishes1`
    FOREIGN KEY (`Dishes_idDishes` , `Dishes_Menu_idMenu`)
    REFERENCES `ruoka_netista`.`Dishes` (`idDishes` , `Menu_idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Order_history1`
    FOREIGN KEY (`Order_history_idOrder_history`)
    REFERENCES `ruoka_netista`.`Order_history` (`idOrder_history`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
